apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      volumes:
      - name: myclaim
        persistentVolumeClaim:
          claimName: myclaim 
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DATABASE
          value: localhost
        - name: WORDPRESS_DB_USER
          value: wp-user-adilet
        - name: WORDPRESS_PASSWORD
          value: password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myclaim
          mountPath: /var/lib/mysql

        resources: {}
status: {}
