apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      name: wordpress      
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env: 
        - name: WORDPRESS_DB_HOST
          value: mysql-lb
        - name: WORDPRESS_DB_PASSWORD
          value: password
        ports:
        - containerPort: 80
          name: wordpress
